# -*- coding: utf-8 -*-
"""sentiment_analysis_python_hotel_reviews.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8Q5ZHA4-O778mqMH6Hxa7vXGT8zuv3N
"""

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

import nltk
import string

from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from sklearn.model_selection import GridSearchCV

import re

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm

from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/train.csv'
df = pd.read_csv(path)
df.head()

df.shape
df = df.drop_duplicates(keep='first')

encoder = LabelEncoder()

df['Is_Response'] = encoder.fit_transform(df['Is_Response'])
df.shape

def get_importantFeatures(sent):
  sent = sent.lower()
  sent = re.sub('\W+','', sent)

  return sent

df['imp_features'] = df['Description'].apply(get_importantFeatures)
df

from sklearn.model_selection import train_test_split

x = df.imp_features
y = df.Is_Response

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 100)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

vector = CountVectorizer()
sv = svm.SVC()
model = Pipeline([('vectorizer',vector),('classifier',sv)])
model.fit(x_train, y_train)
pred = model.predict(x_test)

import seaborn as sns
import matplotlib.pyplot as plt

cm=confusion_matrix(y_test,pred)
conf_matrix=pd.DataFrame(data=cm, columns=['Predicted:0','Predicted:1'],index=['Actual:0','Actual:1'])
plt.figure(figsize = (8,5))

sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='YlGnBu');

print(accuracy_score(y_test,pred))

