# -*- coding: utf-8 -*-
"""nn_mushroom_classification_decision_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_hdUT7z-bw9b_9dJqAEwg4hG5LTQ9-v
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import (train_test_split, StratifiedKFold, cross_val_score, GridSearchCV)
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.metrics import (classification_report, confusion_matrix, roc_auc_score, ConfusionMatrixDisplay, f1_score, accuracy_score)
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

import warnings
warnings.filterwarnings('ignore')

SEED = 42
np.random.seed(SEED)

plt.rcParams.update({
    'figure.figsize': (12, 6),
    'axes.spines.top': False,
    'axes.spines.right': False,
    'font.size': 11,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
})

COLORS = {'edible': '#4CAF50', 'poisonous': '#F44336', 'accent':'#FF9800', 'blue':'#2196F3', 'purple':'#9C27B0'}

print('Ready.')

import os

print("Does /kaggle/input exist?", os.path.exists('/kaggle/input/'))
print("What's in /content?", os.listdir('/content'))

#Finding file path
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/mushroom-classification")

print("Path to dataset files:", path)

#Update path based on output above
csv_path = os.path.join(path, "mushrooms.csv")
df = pd.read_csv(csv_path)
df.head()

print(f'Shape: {df.shape}')
print(f'\nColumn types:')
print(df.dtypes.value_counts())

#Quick checks
print('Missing values:', df.isnull().sum().sum())
print(f'Duplicates: {df.duplicated().sum()}')
print(f'\nTarget distribution:')
print(df['class'].value_counts())
print(f'\nAll features are categorical (single-letter codes).')

#Decode the single letter codes to readable names
decode_maps = {
    'class': {'e':'edible', 'p':'poisonous'},
    'cap-shape': {'b':'bell','c':'conical','x':'convex','f':'flat','k':'knobbed','s':'sunken'},
    'cap-surface': {'f':'fibrous','g':'grooves','y':'scaly','s':'smooth'},
    'cap-color': {'n':'brown','b':'buff','c':'cinnamon','g':'gray','r':'green','p':'pink','u':'purple','e':'red','w':'white','y':'yellow'},
    'bruises': {'t':'yes','f':'no'},
    'odor': {'a':'almond', 'l':'anise', 'c':'creosote', 'y':'fishy', 'f':'foul', 'm':'musty', 'n':'none', 'p':'pungent', 's':'spicy'},
    'gill-attachment': {'a':'attached','f':'free'},
    'gill-spacing': {'c':'close', 'w':'crowded'},
    'gill-size': {'b':'broad', 'n':'narrow'},
    'gill-color': {'k':'black','n':'brown', 'b':'buff', 'h':'chocolate','g':'gray', 'r':'green','o':'orange','p':'pink','u':'purple','e':'red','w':'white','y':'yellow'},
    'stalk-shape': {'e':'enlarging','t':'tapering'},
    'stalk-root': {'b':'bulbous','c':'club','u':'cup','e':'equal','z':'rhizomorphs','r':'rooted','?':'missing'},
    'stalk-surface-above-ring': {'f':'fibrous','y':'scaly','k':'silky','s':'smooth'},
    'stalk-surface-below-ring': {'f':'fibrous','y':'scaly','k':'silky','s':'smooth'},
    'stalk-color-above-ring': {'n':'brown','b':'buff','c':'cinnamon','g':'gray','o':'orange','p':'pink','e':'red','w':'white','y':'yellow'},
    'stalk-color-below-ring': {'n':'brown','b':'buff','c':'cinnamon','g':'gray','o':'orange','p':'pink','e':'red','w':'white','y':'yellow'},
    'veil-type': {'p':'partial','u':'universal'},
    'veil-color': {'n':'brown','o':'orange','w':'white','y':'yellow'},
    'ring-number': {'n':'none','o':'one','t':'two'},
    'ring-type': {'e':'evanescent','f':'flaring','l':'large','n':'none','p':'pendant'},
    'spore-print-color': {'k':'black','n':'brown','b':'buff','h':'chocolate','r':'green','o':'orange','u':'purple','w':'white','y':'yellow'},
    'population': {'a':'abundant','c':'clustered','n':'numerous','s':'scattered','v':'several','y':'solitary'},
    'habitat': {'g':'grasses','l':'leaves','m':'meadows','p':'paths','u':'urban','w':'waste','d':'woods'},
}

df_decoded = df.copy()
for col, mapping in decode_maps.items():
  if col in df_decoded.columns:
    df_decoded[col] = df_decoded[col].map(mapping).fillna(df_decoded[col])

print('Decoded sample:')
df_decoded.head(3)

#Class balance
fig, ax = plt.subplots(figsize=(8, 5))
counts = df_decoded['class'].value_counts()
bars = ax.bar(counts.index, counts.values, color=[COLORS['edible'], COLORS['poisonous']], edgecolor='white', linewidth=1.5)

for bar, val in zip(bars, counts.values):
  ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 30, f'{val} ({val/len(df):.1%})', ha='center', fontweight='bold')
ax.set_ylabel('Count')
ax.set_title('Edible vs Poisonous')
plt.tight_layout()
plt.show()

print('Nearly balanced - no need for class weight adjustments')

#Feature importance
feature_cols = [c for c in df_decoded.columns if c != 'class']

#Use chi-squared-like metric: for each feature, how different is the poison rate across categories?
informativeness = []
for col in feature_cols:
  ct = pd.crosstab(df_decoded[col], df_decoded['class'], normalize='index')
  if 'poisonous' in ct.columns:
    #Range of poison rate across categories
    poison_rates = ct['poisonous']
    info = poison_rates.max() - poison_rates.min()
  else:
    info = 0
  informativeness.append({'feature' : col, 'info':info})

info_df = pd.DataFrame(informativeness).sort_values('info', ascending=True)

fig, ax = plt.subplots(figsize=(10, 8))
ax.barh(info_df['feature'], info_df['info'], color=COLORS['accent'], edgecolor='white')
ax.set_xlabel('Max Posion Rate Difference Across Categories')
ax.set_title('Feature Informativeness - Which Features Seperate Edible From Poisonous?')
plt.tight_layout()
plt.show()

top_5 = info_df.nlargest(5, 'info')['feature'].tolist()
print(f'Most informative features: {top_5}')

#Detailed look at the top 4 features
fig, axes = plt.subplots(2, 2, figsize=(16, 10))

for ax, col in zip(axes.ravel(), top_5[:4]):
    ct = pd.crosstab(df_decoded[col], df_decoded['class'])
    ct = ct.sort_values('poisonous', ascending=False) if 'poisonous' in ct.columns else ct
    ct.plot(kind='bar', stacked=True, ax=ax,
          color=[COLORS['edible'], COLORS['poisonous']], edgecolor='white')
    ax.set_title(col, fontweight='bold')
    ax.set_ylabel('Count')
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right')
    ax.legend(['Edible', 'Poisonous'], fontsize=9)

plt.tight_layout()
plt.show()

# Drop veil-type if it exists and has one unique value
if 'veil-type' in df_decoded.columns and df_decoded['veil-type'].nunique() == 1:
    df_decoded = df_decoded.drop(columns=['veil-type'])
    print('Dropped veil-type (only one unique value).')

feature_cols = [c for c in df_decoded.columns if c != 'class']

# Encode target
y = (df_decoded['class'] == 'poisonous').astype(int).values  # 1=poisonous, 0=edible

# Ordinal encode all categorical features
# Decision Trees handle ordinal encoding well — they just split at thresholds
encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
X = encoder.fit_transform(df_decoded[feature_cols])

# Keep track of category names for tree visualization
category_names = {}
for i, col in enumerate(feature_cols):
    category_names[col] = encoder.categories_[i].tolist()

print(f'Features: {X.shape[1]}')
print(f'Samples: {X.shape[0]}')

#Train,Test,Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=SEED, stratify=y
)

print(f'Train: {X_train.shape[0]} ({y_train.mean():.1%} poisonous)')
print(f'Test: {X_test.shape[0]} ({y_test.mean():.1%} poisonous)')

#Depth 3 tree
dt_shallow = DecisionTreeClassifier(max_depth=3, random_state=SEED)
dt_shallow.fit(X_train, y_train)

acc_shallow = dt_shallow.score(X_test, y_test)
print(f'Depth-3 tree accuracy: {acc_shallow:.4f}')

fig, ax = plt.subplots(figsize=(20,10))
plot_tree(dt_shallow, feature_names=feature_cols,
          class_names=['Edible', 'Poisonous'],
          filled=True, rounded=True, ax=ax,
          fontsize=10, proportion=True)
ax.set_title(f'Decision Tree (max_depth=3) - Accuracy: {acc_shallow:.1%}', fontsize=16)
plt.tight_layout()
plt.show()

#Text version of rules
tree_rules = export_text(dt_shallow, feature_names=feature_cols, max_depth=3)
print('Decision Rules (depth-3 tree)')
print(tree_rules)

#Compare Gini vs Entropy
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)

for criterion in ['gini', 'entropy']:
    dt = DecisionTreeClassifier(max_depth=5, criterion=criterion, random_state=SEED)
    scores = cross_val_score(dt, X_train, y_train, cv=cv, scoring='accuracy')
    print(f'{criterion.capitalize():8s}: CV accuracy = {scores.mean():.4f} ± {scores.std():.4f}')

print('\nNearly identical - Gini is faster to compute, so it\'s the default.')

# Sweep max_depth from 1 to 20
depths = range(1, 21)
train_accs = []
cv_accs = []
n_leaves_list = []

for d in depths:
    dt = DecisionTreeClassifier(max_depth=d, random_state=SEED)
    dt.fit(X_train, y_train)

    train_accs.append(dt.score(X_train, y_train))
    cv_score = cross_val_score(dt, X_train, y_train, cv=cv, scoring='accuracy')
    cv_accs.append(cv_score.mean())
    n_leaves_list.append(dt.get_n_leaves())

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Accuracy vs depth
axes[0].plot(depths, train_accs, '--', color=COLORS['blue'], label='Train', linewidth=2)
axes[0].plot(depths, cv_accs, '-', color=COLORS['accent'], label='CV', linewidth=2)
best_depth = depths[np.argmax(cv_accs)]
axes[0].axvline(best_depth, color='gray', linestyle=':', alpha=0.7)
axes[0].annotate(f'Best depth={best_depth}\nCV={max(cv_accs):.4f}',
                xy=(best_depth, max(cv_accs)), xytext=(best_depth + 3, max(cv_accs) - 0.005),
                arrowprops=dict(arrowstyle='->', color='gray'), fontsize=11)
axes[0].set_xlabel('Max Depth')
axes[0].set_ylabel('Accuracy')
axes[0].set_title('Accuracy vs. Tree Depth')
axes[0].legend(fontsize=11)

# Number of leaves vs depth
axes[1].plot(depths, n_leaves_list, 'o-', color=COLORS['purple'], linewidth=2)
axes[1].set_xlabel('Max Depth')
axes[1].set_ylabel('Number of Leaves')
axes[1].set_title('Tree Complexity vs. Depth')

plt.tight_layout()
plt.show()

print(f'Depth 1 (stump): {train_accs[0]:.3f} train, {cv_accs[0]:.3f} CV, {n_leaves_list[0]} leaves')
print(f'Depth {best_depth} (best): {train_accs[best_depth-1]:.3f} train, {cv_accs[best_depth-1]:.3f} CV, {n_leaves_list[best_depth-1]} leaves')
print(f'Depth 20 (deep): {train_accs[-1]:.3f} train, {cv_accs[-1]:.3f} CV, {n_leaves_list[-1]} leaves')

#Gridsearch for pre-pruning hyperparameters
param_grid = {
    'max_depth' : [3, 5, 7, 10, 15, None],
    'min_samples_split' : [2, 5, 10, 20],
    'min_samples_leaf' : [1, 2, 5, 10],
}

grid = GridSearchCV(
    DecisionTreeClassifier(random_state=SEED),
    param_grid,
    cv=cv,
    scoring='accuracy',
    n_jobs=1,
    return_train_score=True
)
grid.fit(X_train, y_train)

print(f'Best params: {grid.best_params_}')
print(f'Best CV accuracy: {grid.best_score_:.4f}')

#Find the effective alphas
dt_full = DecisionTreeClassifier(random_state=SEED)
dt_full.fit(X_train, y_train)

path = dt_full.cost_complexity_pruning_path(X_train, y_train)
ccp_alphas = path.ccp_alphas
impurities = path.impurities

print(f'Full tree: {dt_full.get_n_leaves()} leaves')
print(f'Number of effective alphas: {len(ccp_alphas)}')
print(f'Alpha range: [{ccp_alphas.min():.6f}, {ccp_alphas.max():.6f}]')

#Train trees for a range of alphas and track performance
alpha_sample = ccp_alphas[::max(1, len(ccp_alphas) // 50)]

train_scores_ccp = []
cv_scores_ccp = []
n_leaves_ccp = []

for alpha in alpha_sample:
    dt = DecisionTreeClassifier(ccp_alpha=alpha, random_state=SEED)
    dt.fit(X_train, y_train)
    train_scores_ccp.append(dt.score(X_train, y_train))
    cv_score = cross_val_score(dt, X_train, y_train, cv=cv, scoring='accuracy')
    cv_scores_ccp.append(cv_score.mean())
    n_leaves_ccp.append(dt.get_n_leaves())

best_alpha_idx = np.argmax(cv_scores_ccp)
best_alpha = alpha_sample[best_alpha_idx]

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(alpha_sample, train_scores_ccp, '--', color=COLORS['blue'], label='Train', linewidth=2)
axes[0].plot(alpha_sample, cv_scores_ccp, '-', color=COLORS['accent'], label='CV', linewidth=2)
axes[0].axvline(best_alpha, color='gray', linestyle=':', alpha=0.7)
axes[0].set_xlabel('ccp_alpha')
axes[0].set_ylabel('Accuracy')
axes[0].set_title('Cost-Complexity Pruning Path')
axes[0].legend(fontsize=11)

axes[1].plot(alpha_sample, n_leaves_ccp, 'o-', color=COLORS['purple'], linewidth=2, markersize=4)
axes[1].axvline(best_alpha, color='gray', linestyle=':', alpha=0.7)
axes[1].set_xlabel('ccp_alpha')
axes[1].set_ylabel('Number of Leaves')
axes[1].set_title('Tree Complexity vs. Pruning Strength')

plt.tight_layout()
plt.show()

print(f'Best alpha: {best_alpha:.6f}')
print(f'Best CV accuracy: {cv_scores_ccp[best_alpha_idx]:.4f}')
print(f'Leaves at best alpha: {n_leaves_ccp[best_alpha_idx]}')

#Train the pruned tree
dt_pruned = DecisionTreeClassifier(ccp_alpha=best_alpha, random_state=SEED)
dt_pruned.fit(X_train, y_train)

y_pred_pruned = dt_pruned.predict(X_test)

print(f'=== Pruned Decision Tree (alpha={best_alpha:.6f}) ===')
print(f'Leaves: {dt_pruned.get_n_leaves()}, Depth: {dt_pruned.get_depth()}')
print(f'\n{classification_report(y_test, y_pred_pruned, target_names=["Edible", "Poisonous"])}')

#Compare feature importance: full tree vs pruned tree
fig, axes = plt.subplots(1, 2, figsize=(16, 7))

for ax, model, title in [(axes[0], dt_full, 'Full Tree'),
                         (axes[1], dt_pruned, 'Pruned Tree')]:
    imp = pd.DataFrame({
        'feature' : feature_cols,
        'importance' : model.feature_importances_
    }).sort_values('importance', ascending=True)

    imp_nonzero = imp[imp['importance'] > 0]
    ax.barh(imp_nonzero['feature'], imp_nonzero['importance'],
            color=COLORS['accent'], edgecolor='white')
    ax.set_xlabel('Feature Importance (Gini)')
    ax.set_title(f'{title} ({model.get_n_leaves()} leaves)', fontweight='bold')

plt.tight_layout()
plt.show()

#Which features does the pruned tree use?
used = imp[imp['importance'] > 0]['feature'].tolist()
unused = imp[imp['importance'] == 0]['feature'].tolist()
print(f'Pruned tree uses {len(used)} features: {used}')
print(f'Ignores {len(unused)} features: {unused[:5]}...')

#Visualise the final pruned tree
if dt_pruned.get_depth() <= 6:
    fig, ax = plt.subplots(figsize=(24, 12))
    plot_tree(dt_pruned, feature_names=feature_cols,
             class_names=['Edible', 'Poisonous'],
             filled=True, rounded=True, ax=ax,
             fontsize=8, proportion=True)
    ax.set_title(f'Pruned Decision Tree (depth={dt_pruned.get_depth()}, leaves={dt_pruned.get_n_leaves()})',
                 fontsize=16)
    plt.tight_layout()
    plt.show()
else:
  fig, ax = plt.subplots(figsize=(20, 10))
  plot_tree(dt_pruned, feature_names=feature_cols,
            class_names=['Edible', 'Poisonous'],
            filled=True, rounded=True, ax=ax,
            fontsize=9, proportion=True, max_depth=4)
  ax.set_title(f'Pruned Tree - Top 4 Levels (full depth={dt_pruned.get_depth()})', fontsize=16)
  plt.tight_layout()
  plt.show()

rules = export_text(dt_pruned, feature_names=feature_cols, max_depth=5)
print('Top decision rules:')
print(rules[:2000])

models = {
    f'Decision Tree (pruned)': dt_pruned,
    f'Decision Tree (full)': DecisionTreeClassifier(random_state=SEED),
    'Random Forest (200)': RandomForestClassifier(n_estimators=200, random_state=SEED, n_jobs=-1),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=200, random_state=SEED),
    'Logistic Regression': LogisticRegression(random_state=SEED, max_iter=100),
}

comparison = []
for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='accuracy')
    comparison.append({
        'Model' : name,
        'CV Accuracy' : scores.mean(),
        'Std' : scores.std()
    })

    comp_df = pd.DataFrame(comparison).sort_values('CV Accuracy', ascending=False)
    print(comp_df.to_string(index=False, float_format='%.4f'))

#Visual comparison
fig, ax = plt.subplots(figsize=(10, 5))
colors_bar = [COLORS['accent'] if 'Decision' in m else COLORS['blue'] for m in comp_df['Model']]
ax.barh(comp_df['Model'], comp_df['CV Accuracy'], xerr=comp_df['Std'],
        color=colors_bar, edgecolor='white', capsize=4)
ax.set_xlabel('CV Accuracy')
ax.set_title('Decision Tree vs Other Models')
ax.set_xlim(comp_df['CV Accuracy'].min() - 0.02, 1.005)
plt.tight_layout()
plt.show()

print('On this dataset, a single pruned tree is surprisingly competitive.')
print('That\'s because the mushroom features are highly informative - odor alone')
print('gets you most of the way. Not all datasets are this clean.')

